name: Dariodip's Advent of Code CI

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: Show rust version
      run: rustc --version
    - name: Test and check (stable)
      run: |
        cargo make test
