name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy -- -D warnings
  
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose

  build:
    runs-on: ubuntu-latest
    needs: [check, tests]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

  benchmark:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Run benchmarks
      run: cargo bench --verbose
